### ISSUE TITLE
does this work with laravel 8.x?

### ISSUE THREAD

**Issue by torian257x** [michaeldyrynda/laravel-make-user#18]
does this work with laravel 8.x?

**Comment by michaeldyrynda** [comment]
It seems [yes](https://github.com/michaeldyrynda/laravel-make-user/pull/17), but I never tagged a 8.x-compatible release. 

I will review and do so a bit later!

**Comment by michaeldyrynda** [comment]
Tagged [7.3.0](https://github.com/michaeldyrynda/laravel-make-user/releases/tag/7.3.0) that supports Laravel 8.
