### ISSUE TITLE
Please join forces with laravel-cli-user

### ISSUE THREAD

**Issue by COLABORATI** [michaeldyrynda/laravel-make-user#2]
Very nice package, thank you very much!

It would be great if you would like to join forces with
[laravel-cli-user](https://github.com/subdesign/laravel-cli-user)
as it seems there is overlapping and complementary functionality.  

Thank you very much for your attention!

**Comment by michaeldyrynda** [comment]
Seems that other package is doing more work - listing, deleting users, etc.

This one is focussed on the act of creating new users - mostly for scaffolding purposes, as in projects I was building I needed the ability to create my initial admin users, then managed the rest via a UI in the app.
